<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <VersionPrefix>1.2</VersionPrefix>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <BaseOutputPath>bin\</BaseOutputPath>
	<GenerateApplicationDefinition>false</GenerateApplicationDefinition>
    <StartupObject>JTSA.App</StartupObject>
    <ApplicationIcon>Resources\jtsa.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
	  <ApplicationDefinition Remove="App.xaml" />
	  <Page Include="App.xaml">
		  <Generator>MSBuild:Compile</Generator>
		  <SubType>Designer</SubType>
	  </Page>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
	<PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="obs-websocket-dotnet" Version="5.0.1" />
    <PackageReference Include="TwitchLib.Api" Version="3.10.1-preview.199.347b75c" />
    <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.9.0-preview.91.e7a2a33" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\jtsa.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
