// <auto-generated />
using System;
using JTSA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JTSA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810052614_expansion_db_add")]
    partial class expansion_db_add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("JTSA.Models.T_ChannelPointPresetHeader", b =>
                {
                    b.Property<long>("PresetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PresetId");

                    b.ToTable("T_ChannelPointPresetHeader");
                });

            modelBuilder.Entity("JTSA.Models.T_ChannelPointPresetItem", b =>
                {
                    b.Property<long>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PresetId", "RewardId");

                    b.ToTable("T_ChannelPointPresetItem");
                });

            modelBuilder.Entity("JTSA.Models.T_ChatUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TakeBits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("T_ChatUser");
                });

            modelBuilder.Entity("JTSA.Models.T_GamePlaylistHeader", b =>
                {
                    b.Property<long>("GamePlayListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePlayListName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailCategoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GamePlayListId");

                    b.ToTable("T_GamePlaylistHeader");
                });

            modelBuilder.Entity("JTSA.Models.T_GamePlaylistItem", b =>
                {
                    b.Property<long>("GamePlayListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GamePlayListId", "CategoryId");

                    b.ToTable("T_GamePlaylistItem");
                });

            modelBuilder.Entity("JTSA.Models.T_StreamExpansionHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerChannelPointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("T_StreamExpansionHeader");
                });

            modelBuilder.Entity("JTSA.Models.T_StreamExpansionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("HeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id", "HeaderId");

                    b.ToTable("T_StreamExpansionItem");
                });

            modelBuilder.Entity("M_Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxArtUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChannelPointPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamHeaderArtUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("M_Category");
                });

            modelBuilder.Entity("M_ChannelPoint", b =>
                {
                    b.Property<string>("RewardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManageable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RewardId");

                    b.ToTable("M_ChannelPoint");
                });

            modelBuilder.Entity("M_Setting", b =>
                {
                    b.Property<int>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("M_Setting");
                });

            modelBuilder.Entity("M_TitleTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("M_TitleTag");
                });

            modelBuilder.Entity("M_User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfielImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("M_User");
                });

            modelBuilder.Entity("T_TitleText", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryBoxArtUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("T_TitleText");
                });
#pragma warning restore 612, 618
        }
    }
}
