// <auto-generated />
using System;
using JTSA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JTSA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727103651_M_GamePlayListandT_GamePlayListLink")]
    partial class M_GamePlayListandT_GamePlayListLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("JTSA.Models.M_GamePlayList", b =>
                {
                    b.Property<int>("GamePlayListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePlayListName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailCategoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GamePlayListId");

                    b.ToTable("M_GamePlayList");
                });

            modelBuilder.Entity("JTSA.Models.T_GamePlayListLink", b =>
                {
                    b.Property<int>("GamePlayListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamePlayListId", "CategoryId");

                    b.ToTable("T_GamePlayListLink");
                });

            modelBuilder.Entity("M_Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxArtUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamHeaderUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("M_CategoryList");
                });

            modelBuilder.Entity("M_Friend", b =>
                {
                    b.Property<string>("BroadcastId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BroadcastId");

                    b.ToTable("M_FriendList");
                });

            modelBuilder.Entity("M_Setting", b =>
                {
                    b.Property<int>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("M_SettingList");
                });

            modelBuilder.Entity("M_StreamWindow", b =>
                {
                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppExePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcessName");

                    b.ToTable("M_StreamWindowList");
                });

            modelBuilder.Entity("M_TitleTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("M_TitleTagList");
                });

            modelBuilder.Entity("M_TitleText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryBoxArtUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUseDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("M_TitleTextList");
                });
#pragma warning restore 612, 618
        }
    }
}
